# Generated by Django 5.1.3 on 2025-04-05 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpikeZoneApiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SpikeZoneApiApp.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
    ]
