# Generated by Django 5.1.3 on 2025-04-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpikeZoneApiApp', '0003_order_razorpay_order_id_order_razorpay_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(default=8, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default=8, max_length=15),
            preserve_default=False,
        ),
    ]
